### ISSUE TITLE
Missing arm64/v8 architecture

### ISSUE THREAD

**Issue by ianschmitz** [nlmatics/nlm-ingestor#13]
When trying to pull on a M1 MacBook i get the following error:

```
$ docker pull ghcr.io/nlmatics/nlm-ingestor:latest
latest: Pulling from nlmatics/nlm-ingestor
no matching manifest for linux/arm64/v8 in the manifest list entries
```

Looking at the action that builds and deploys the image, it looks like `platforms` isn't included: https://github.com/nlmatics/nlm-ingestor/blob/8f1bcb46ba7cc3dfe0d8c60a150a32fe887be78a/.github/workflows/docker-publish.yml#L73-L79

However it was set above when setting up docker buildx: https://github.com/nlmatics/nlm-ingestor/blob/8f1bcb46ba7cc3dfe0d8c60a150a32fe887be78a/.github/workflows/docker-publish.yml#L48

I'm not entirely sure what `platforms` does in the context of the `setup-buildx-action`, but [looking at the docs for multi-platform build](https://docs.docker.com/build/ci/github-actions/multi-platform/) it looks like if QEMU was setup as an action prior to build, we could simply specify the `platforms` as part of the `build-push-action`.

Would you accept a PR to fix this and deploy a multi-platform image? If so what are the platforms you would like to target?

**Comment by ansukla** [comment]
@ianschmitz - that will be awesome. Please create the PR. You can also use docker pull --platform linux/x86_64 ghcr.io/nlmatics/nlm-ingestor:latest as a workaround, but it will be great to fix this correctly in the repo. Thanks for the offer.
