### ISSUE TITLE
Health endpoint

### ISSUE THREAD

**Issue by jpbalarini** [nlmatics/nlm-ingestor#4]
I deployed this as an ECS service, but ECS needs a way to check the health of the service (to determine if the deployment was successful). Generally, you can do something like this:
```
{
    "Command": [
        "CMD-SHELL",
        "curl -f http://localhost:5001/ || exit 1"
    ],
    "Interval": 30,
    "Retries": 5,
    "StartPeriod": 20,
    "Timeout": 5
}
```

but this does not work since the only defined endpoint is a POST to `/api/parseDocument` that requires an input file. Is there any way of doing this? A GET to `/` returns 404. What about adding an endpoint to `/` that just returns 200 to check service status?
Thanks!

**Comment by ansukla** [comment]
This is a good idea. You can submit a PR for this change. Alternatively, you can write your own service endpoint with your choice of WSGI and create a docker image based on the one provided here.

**Comment by potus84** [comment]
@ansukla can you build a new release with this health-check functionality?
I noticed that the v.0.1.6 did not include this new PR.
