### ISSUE TITLE
bbox error in BlockRender

### ISSUE THREAD

**Issue by livelxw** [nlmatics/nlm-ingestor#52]
`table_block` maybe not contains `left` and `top`.
https://github.com/nlmatics/nlm-ingestor/blob/cdfc6393e6acd624f2b6bc0489e5e2f9918b4b40/nlm_ingestor/ingestor/visual_ingestor/block_renderer.py#L342-L351

**Comment by kiran-nlmatics** [comment]
@livelxw, I have made some changes and there should not be a bbox error. Please verify once with the file you were trying to ingest.

**Comment by livelxw** [comment]
Fixed.
